name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The version to release (e.g., '20240414')."
        type: string
      sha:
        description: "The full SHA of the commit to be released (e.g., 'd09ff921d92d6da8d8a608eaa850dc8c0f638194')."
        type: string
      dry-run:
        description: "Whether to run the release process without actually releasing."
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: extractions/setup-just@v2
      - uses: Swatinem/rust-cache@v2

      # Perform a release in dry-run mode.
      - run: just release-dry-run ${{ secrets.GITHUB_TOKEN }} ${{ github.event.inputs.sha }} ${{ github.event.inputs.tag }}
        if: ${{ github.event.inputs.dry-run }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Perform a release, creating a GitHub release and uploading the relevant artifacts.
      - run: just release ${{ secrets.GITHUB_TOKEN }} ${{ github.event.inputs.sha }} ${{ github.event.inputs.tag }}
        if: ${{ !github.event.inputs.dry-run }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
